#general
PIC_ENHANCEMENT_ITERATION = 15
HORIZONTAL_LINE_LENGTH = 200
VERTICAL_LINE_LENGTH = 150

#get_cells
FROM_LINE_OFFSET = 1

#get_lines
LINE_SPACE_VERTICAL = 70
LINE_SPACE_HORIZONTAL = 25
MODE_PERFECT_SPREADSHEET = "perfect"
MODE_IRREGULAR_SPREADSHEET = "irregular"
MODE_GET_LINES_WITHOUT_AVERAGING = "without_averaging"
