#general
PIC_ENHANCEMENT_ITERATION = 15
HORIZONTAL_LINE_LENGTH = 200
VERTICAL_LINE_LENGTH = 100
LINE_COLOR = (0,0,255)

#get_cells
FROM_LINE_OFFSET = 1
ATTEMPT_IMAGE_IMPROVEMENT = False

#get_lines
LINE_SPACE_VERTICAL = 70
LINE_SPACE_HORIZONTAL = 25
MODE_PERFECT_SPREADSHEET = "perfect"
MODE_IRREGULAR_SPREADSHEET = "irregular"
MODE_GET_LINES_WITHOUT_AVERAGING = "without_averaging"

VERTICAL_INITIAL_DILATION = (8,1)
VERTICAL_INITIAL_ERODE = (10,1)
VERTICAL_COMMON_DILATION = (8,3)
VERTICAL_COMMON_ERODE =(10,1)

HORIZONTAL_INITIAL_DILATION = (1,4)
HORIZONTAL_INITIAL_ERODE = (1,8)
HORIZONTAL_COMMON_DILATION = (3,4)
HORIZONTAL_COMMON_ERODE =(1,8)
