#general
PIC_ENHANCEMENT_ITERATION = 4
HORIZONTAL_LINE_LENGTH = 250
VERTICAL_LINE_LENGTH = 150
LINE_COLOR = (0,0,0)

#get_cells
FROM_LINE_OFFSET = 1
ATTEMPT_IMAGE_IMPROVEMENT = True

#get_lines
LINE_SPACE_VERTICAL = 35
LINE_SPACE_HORIZONTAL = 15
MODE_PERFECT_SPREADSHEET = "perfect"
MODE_IRREGULAR_SPREADSHEET = "irregular"
MODE_GET_LINES_WITHOUT_AVERAGING = "without_averaging"

VERTICAL_INITIAL_DILATION = (3,1)
VERTICAL_INITIAL_ERODE = (25,1)
VERTICAL_COMMON_DILATION = (5,3)
VERTICAL_COMMON_ERODE =(3,1)

HORIZONTAL_INITIAL_DILATION = (1,4)
HORIZONTAL_INITIAL_ERODE = (1,45)
HORIZONTAL_COMMON_DILATION = (3,10)
HORIZONTAL_COMMON_ERODE =(1,3)
